name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.erlang }}-ubuntu-${{ matrix.ubuntu }}

    name: Elixir ${{ matrix.elixir }} / Erlang ${{ matrix.erlang }} and Ubuntu ${{matrix.ubuntu}}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Older versions with compatible Erlang/Ubuntu
          - elixir: "1.7.4"
            erlang: "22.3.4.26"
            ubuntu: "focal-20240530"
          - elixir: "1.8.2"
            erlang: "22.3.4.26"
            ubuntu: "focal-20240530"
          - elixir: "1.9.4"
            erlang: "22.3.4.26"
            ubuntu: "focal-20240530"
          - elixir: "1.10.4"
            erlang: "22.3.4.26"
            ubuntu: "focal-20240530"
          - elixir: "1.11.4"
            erlang: "24.3.4.17"
            ubuntu: "focal-20240530"
          - elixir: "1.12.3"
            erlang: "24.3.4.17"
            ubuntu: "focal-20240530"
          # Newer versions with recent Erlang/Ubuntu
          - elixir: "1.13.4"
            erlang: "25.3.2.14"
            ubuntu: "jammy-20240530"
          - elixir: "1.14.5"
            erlang: "25.3.2.14"
            ubuntu: "jammy-20240530"
          - elixir: "1.15.8"
            erlang: "26.2.5.2"
            ubuntu: "jammy-20240530"
          - elixir: "1.16.3"
            erlang: "26.2.5.2"
            ubuntu: "jammy-20240530"
          - elixir: "1.17.3"
            erlang: "27.1.2"
            ubuntu: "jammy-20240530"

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Node.js
        run: |-
          apt-get update
          apt-get install -y nodejs
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: deps/
          key: dependencies-${{ matrix.elixir }}-erlang-${{ matrix.erlang }}-${{ hashFiles('mix.lock') }}
      
      - name: Cache dialyzer plt  
        uses: actions/cache@v4
        with:
          path: _build/
          key: build-elixir-${{ matrix.elixir }}-erlang-${{ matrix.erlang }}-${{ hashFiles('mix.lock') }}
      
      - name: Install dependencies
        run: |-
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Check format
        if: (!startsWith(matrix.elixir, '1.7'))
        run: mix format --check-formatted

      - name: Run static code analysis
        run: mix credo --strict

      - name: Run dialyzer
        run: mix dialyzer
       
      - name: Run tests
        run: mix test --cover
