name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.erlang }}-ubuntu-${{ matrix.ubuntu }}

    name: Elixir ${{ matrix.elixir }} / Erlang ${{ matrix.erlang }} and Ubuntu ${{matrix.ubuntu}}

    strategy:
      fail-fast: false
      matrix:
        elixir: ["1.10.3", "1.9.4", "1.8.2", "1.7.4", "1.6.6"]
        erlang: ["21.3.8"]
        ubuntu: ["bionic-20200219"]

    steps:
      - uses: actions/checkout@v1.0.0
      - name: Install dependencies
        run: |-
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Check format
        if: (startsWith(matrix.elixir, '1.6') || startsWith(matrix.elixir, '1.7')) == false
        run: mix format --check-formatted

      - name: Run tests
        run: |-
          mix test --cover
